name: "Build and Push"
description: "Build and Push container images to registry"
inputs:
  username:
    description: "Registry username"
    required: true
  password:
    description: "Registry password"
    required: true
  registry_url:
    description: "Registry URL"
    required: true
  container_image_name:
    description: "Image name"
    required: true
  container_image_version:
    description: "Image version"
    required: true
  build_context:
    description: "Build context"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Login to registry"
      run: echo ${{ inputs.password }} | docker login ${{ inputs.registry_url }} -u ${{ inputs.username }} --password-stdin
      shell: bash

    - name: "Build image"
      run: docker build -t ${{ inputs.registry_url }}/${{ inputs.container_image_name }}:${{ inputs.container_image_version }} ${{ inputs.build_context }}
      shell: bash

    - name: "Push image"
      run: docker push ${{ inputs.registry_url }}/${{ inputs.container_image_name }}:${{ inputs.container_image_version }}
      shell: bash