name: Build and push mkdocs openshift container to OpenShift

env:
  OPENSHIFT_PROJECT: docs
  ACC_REGISTRY_URL: registry.cp-acc.its.uu.nl
  PRD_REGISTRY_URL: registry.cp.its.uu.nl
  IMAGE_NAME: docs
  MAJOR_VERSION: 1

on:
  #  push:
  #    branches: [ "main" ]
  #  pull_request:
  #    branches: [ "main" ]
  workflow_dispatch:

jobs:
  acceptance:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    environment:
      name: acceptance
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: Check if we can ping the registry
        run: |
          ping -c 5 ${{ env.ACC_REGISTRY_URL }}
          ping -c 5 ${{ env.PRD_REGISTRY_URL }}
        shell: bash

      - name: "Login to registry"
        run: echo ${{ secrets.SA_DEVOPS_TOKEN }} | docker login ${{ env.ACC_REGISTRY_URL }} -u ${{ secrets.OPENSHIFT_USERNAME }} --password-stdin
        shell: bash

      - name: "Build image"
        run: docker build -t ${{ env.ACC_REGISTRY_URL }}/${{ env.OPENSHIFT_PROJECT }}/${{ env.IMAGE_NAME }}:dev .
        shell: bash

      - name: "Push image"
        run: docker push ${{ env.ACC_REGISTRY_URL }}/${{ env.OPENSHIFT_PROJECT }}/${{ env.IMAGE_NAME }}:dev
        shell: bash

  production:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: production
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Login to registry"
        run: echo ${{ secrets.SA_DEVOPS_TOKEN }} | docker login ${{ env.PRD_REGISTRY_URL }} -u ${{ secrets.OPENSHIFT_USERNAME }} --password-stdin
        shell: bash

      - name: "Build image"
        run: docker build -t ${{ env.PRD_REGISTRY_URL }}/${{ env.OPENSHIFT_PROJECT }}/${{ env.IMAGE_NAME }}:stable .
        shell: bash

      - name: "Push image"
        run: docker push ${{ env.PRD_REGISTRY_URL }}/${{ env.OPENSHIFT_PROJECT }}/${{ env.IMAGE_NAME }}:stable
        shell: bash
