name: Build and push public docs

env:
  OPENSHIFT_PROJECT: docs
  ACC_REGISTRY_URL: registry.cp-acc.its.uu.nl
  PRD_REGISTRY_URL: registry.cp.its.uu.nl
  IMAGE_NAME: docs
  DEPLOYMENT_NAME: docs-public
  MAJOR_VERSION: 1
  # Installs the latest release of oc with the major version 4.
  # This is equivalent to "4.x" or "^4".
  OC_CLIENT_VERSION: "4"
  ACC_API_URL: api.cl01.cp-acc.its.uu.nl
  PRD_API_URL: api.cl01.cp.its.uu.nl

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "Dockerfile"
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - updated
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "Dockerfile"
  workflow_dispatch:

jobs:
  acceptance:
    name: Acceptance Build&Push
    runs-on: self-hosted
    environment:
      name: acceptance
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - name: "Install CLI tools from OpenShift Mirror"
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: "mirror"
          oc: ${{ env.OC_CLIENT_VERSION }}

      - name: "Build image"
        run: docker build -t ${{ env.ACC_REGISTRY_URL }}/${{ env.OPENSHIFT_PROJECT }}/${{ env.IMAGE_NAME }}:dev .
        shell: bash

      - name: "Login to registry"
        run: echo ${{ secrets.SA_DEVOPS_TOKEN_ACC }} | docker login ${{ env.ACC_REGISTRY_URL }} -u ${{ secrets.OPENSHIFT_USERNAME }} --password-stdin
        shell: bash

      - name: "Push image"
        run: docker push ${{ env.ACC_REGISTRY_URL }}/${{ env.OPENSHIFT_PROJECT }}/${{ env.IMAGE_NAME }}:dev
        shell: bash

      - name: "Authenticate to OpenShift"
        run: oc login --token=${{ secrets.SA_DEVOPS_TOKEN_ACC }} --server=${{ env.ACC_API_URL }}:6443

      - name: "OpenShift restart deployment"
        run: oc delete pods --all --namespace ${{ env.OPENSHIFT_PROJECT }}

  production:
    runs-on: self-hosted
    name: Production Build&Push
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: acceptance
    environment:
      name: production
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - name: "Install CLI tools from OpenShift Mirror"
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: "mirror"
          oc: ${{ env.OC_CLIENT_VERSION }}

      - name: "Build image"
        run: docker build -t ${{ env.PRD_REGISTRY_URL }}/${{ env.OPENSHIFT_PROJECT }}/${{ env.IMAGE_NAME }}:stable .
        shell: bash

      - name: "Login to registry"
        run: echo ${{ secrets.SA_DEVOPS_TOKEN }} | docker login ${{ env.PRD_REGISTRY_URL }} -u ${{ secrets.OPENSHIFT_USERNAME }} --password-stdin
        shell: bash

      - name: "Push image"
        run: docker push ${{ env.PRD_REGISTRY_URL }}/${{ env.OPENSHIFT_PROJECT }}/${{ env.IMAGE_NAME }}:stable
        shell: bash

      - name: "Authenticate to OpenShift"
        run: oc login --token=${{ secrets.SA_DEVOPS_TOKEN }} --server=${{ env.PRD_API_URL }}:6443

      - name: "OpenShift restart deployment"
        run: oc delete pods --all --namespace ${{ env.OPENSHIFT_PROJECT }}
